"""account description account_type removed

Revision ID: 639066e00552
Revises: fbeaca335957
Create Date: 2025-04-23 10:03:02.740103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '639066e00552'
down_revision: Union[str, None] = 'fbeaca335957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FK__accounts__type_i__308E3499', 'accounts', type_='foreignkey')
    op.drop_table('account_types')
    op.add_column('accounts', sa.Column('description', sa.String(length=255), nullable=True))
    op.drop_column('accounts', 'type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_types',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.VARCHAR(length=50, collation='Cyrillic_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='FK__account_t__user___52E34C9D', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='PK__account___3213E83F3EE875CA')
    )
    op.add_column('accounts', sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('FK__accounts__type_i__308E3499', 'accounts', 'account_types', ['type_id'], ['id'])
    op.drop_column('accounts', 'description')
    # ### end Alembic commands ###
