"""account_type_upgrade

Revision ID: c6bec6d34c8b
Revises: e366b4a03f04
Create Date: 2025-04-19 13:51:40.072308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6bec6d34c8b'
down_revision: Union[str, None] = 'e366b4a03f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_types', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_types', 'user_id')
    # ### end Alembic commands ###
