"""account_type_upgrade_constraints

Revision ID: e3ec7b91fec4
Revises: c6bec6d34c8b
Create Date: 2025-04-19 13:55:09.179865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3ec7b91fec4'
down_revision: Union[str, None] = 'c6bec6d34c8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account_types', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
    op.create_foreign_key(None, 'account_types', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account_types', type_='foreignkey')
    op.alter_column('account_types', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
